var FormModel_NewInvoice = function () {
    var self = this;
    self.ID = ko.observable();
    self.ID_HoaDon = ko.observable();
    self.IDRandom = ko.observable();
    self.LoaiHoaDon = ko.observable(1);
    self.MaHoaDon = ko.observable();
    self.MaHoaDonDB = ko.observable();
    self.NgayLapHoaDon = ko.observable(moment(new Date()).format('YYYY-MM-DD HH:mm'));
    self.TongTienHang = ko.observable(0);
    self.PhaiThanhToan = ko.observable(0);
    self.TongGiamGia = ko.observable(0);
    self.DaThanhToan = ko.observable(0);
    self.KhachDaTra = ko.observable(0);
    self.PTThue = ko.observable(0);
    self.TongTienThue = ko.observable(0);
    self.PTChiPhi = ko.observable(0);
    self.TongChiPhi = ko.observable(0);
    self.DVTinhPhiDV = ko.observable('%'); // donvitinh phidv (use at nhahang)
    self.DienGiai = ko.observable('');
    self.DVTinhGiam = ko.observable('%');
    self.TongChietKhau = ko.observable(0);
    self.IsKhuyenMaiHD = ko.observable(false);
    self.ID_KhuyenMai = ko.observable(null);
    self.ID_NhomDTApplySale = ko.observable(null);
    self.KhuyeMai_GiamGia = ko.observable(0);
    self.TienThua = ko.observable(0);
    self.KhuyenMai_GhiChu = ko.observable('');
    self.TongGiamGiaKM_HD = ko.observable(0);
    self.NgayApDungGoiDV = ko.observable(moment().format('DD/MM/YYY'));
    self.HanSuDungGoiDV = ko.observable(moment().add('years', 1).format('DD/MM/YYY'));
    self.TienMat = ko.observable(0);
    self.TienATM = ko.observable(0);
    self.TienGui = ko.observable(0);
    self.TienTheGiaTri = ko.observable(0);
    self.DiemQuyDoi = ko.observable(0);
    self.TTBangDiem = ko.observable(0);
    self.StatusOffline = ko.observable(0);
    self.SoLuongKhachHang = ko.observable(0);

    self.PhaiThanhToanDB = ko.observable(0);
    self.TongTienMua = ko.observable(0);
    self.TongTienTra = ko.observable(0);
    self.DaTraKhach = ko.observable(0);
    self.PhaiTraKhach = ko.observable(0);
    self.HoanTraThuKhac = ko.observable(0);
    self.PTGiamDB = ko.observable(0);
    self.TongGiamGiaDB = ko.observable(0);
    self.PTThueDB = ko.observable(0);
    self.TongThueDB = ko.observable(0);
    self.TongGiaGocHangTra = ko.observable(0);
    self.HoanTraTamUng = ko.observable(0);
    self.MaHoaDonTH_NVien = ko.observable('');
    self.ID_TaiKhoanPos = ko.observable(null);
    self.ID_TaiKhoanChuyenKhoan = ko.observable(null);

    self.SetData = function (item) {
        self.ID(item.ID);
        self.ID_HoaDon(item.ID_HoaDon);
        self.IDRandom(item.IDRandom);
        self.LoaiHoaDon(item.LoaiHoaDon);
        self.MaHoaDon(item.MaHoaDon);
        self.MaHoaDonDB(item.MaHoaDonDB);
        self.NgayLapHoaDon(item.NgayLapHoaDon);
        self.TongTienHang(item.TongTienHang);
        self.PhaiThanhToan(item.PhaiThanhToan);
        self.TongGiamGia(item.TongGiamGia);
        self.DaThanhToan(item.DaThanhToan);
        self.KhachDaTra(item.KhachDaTra);
        self.PTThue(item.PTThue);
        self.TongTienThue(item.TongTienThue);
        self.DienGiai(item.DienGiai);
        self.DVTinhGiam(item.DVTinhGiam);
        self.TongChietKhau(item.TongChietKhau);
        self.IsKhuyenMaiHD(item.IsKhuyenMaiHD);
        self.ID_KhuyenMai(item.ID_KhuyenMai);
        self.ID_NhomDTApplySale(item.ID_NhomDTApplySale);
        self.KhuyeMai_GiamGia(item.KhuyeMai_GiamGia);
        self.TienThua(item.TienThua);
        self.KhuyenMai_GhiChu(item.KhuyenMai_GhiChu);
        self.TongGiamGiaKM_HD(item.TongGiamGiaKM_HD);
        self.NgayApDungGoiDV(item.NgayApDungGoiDV);
        self.HanSuDungGoiDV(item.HanSuDungGoiDV);
        self.TienMat(item.TienMat);
        self.TienATM(item.TienATM);
        self.TienGui(item.TienGui);
        self.TienTheGiaTri(item.TienTheGiaTri);
        self.DiemQuyDoi(item.DiemQuyDoi);
        self.TTBangDiem(item.TTBangDiem);
        self.StatusOffline(item.StatusOffline);
        self.SoLuongKhachHang(item.SoLuongKhachHang);

        self.PhaiThanhToanDB(item.PhaiThanhToanDB);
        self.TongTienMua(item.TongTienMua);
        self.TongTienTra(item.TongTienTra);
        self.DaTraKhach(item.DaTraKhach);
        self.PhaiTraKhach(item.HoanTraTamUng);// assign = hoantra
        self.HoanTraThuKhac(item.HoanTraThuKhac);
        self.PTThueDB(item.PTThueDB);
        self.TongThueDB(item.TongThueDB);
        self.TongGiaGocHangTra(item.TongGiaGocHangTra);
        self.PTGiamDB(item.PTGiamDB);
        self.TongGiamGiaDB(item.TongGiamGiaDB);
        self.PTChiPhi(item.PTChiPhi);
        self.TongChiPhi(item.TongChiPhi);
        self.DVTinhPhiDV(item.DVTinhPhiDV);
        self.HoanTraTamUng(item.HoanTraTamUng);
        self.MaHoaDonTH_NVien(item.MaHoaDonTH_NVien);
        self.ID_TaiKhoanPos(item.ID_TaiKhoanPos);
        self.ID_TaiKhoanChuyenKhoan(item.ID_TaiKhoanChuyenKhoan);
    }
}
