//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanHang24vnContext : DbContext
    {
        public BanHang24vnContext()
            : base("name=BanHang24vnContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CuaHangDangKy> CuaHangDangKies { get; set; }
        public virtual DbSet<DM_HangHoa> DM_HangHoa { get; set; }
        public virtual DbSet<DM_NhomHangHoa> DM_NhomHangHoa { get; set; }
        public virtual DbSet<DM_PhanLoaiHangHoaDichVu> DM_PhanLoaiHangHoaDichVu { get; set; }
        public virtual DbSet<DM_QuanHuyen> DM_QuanHuyen { get; set; }
        public virtual DbSet<DM_QuocGia> DM_QuocGia { get; set; }
        public virtual DbSet<DM_TinhThanh> DM_TinhThanh { get; set; }
        public virtual DbSet<DM_VungMien> DM_VungMien { get; set; }
        public virtual DbSet<DonViQuiDoi> DonViQuiDois { get; set; }
        public virtual DbSet<HT_Quyen> HT_Quyen { get; set; }
        public virtual DbSet<HT_Quyen_NganhNgheKinhDoanh> HT_Quyen_NganhNgheKinhDoanh { get; set; }
        public virtual DbSet<News_CategoriesType> News_CategoriesType { get; set; }
        public virtual DbSet<News_EmployeeList> News_EmployeeList { get; set; }
        public virtual DbSet<News_FunctionList> News_FunctionList { get; set; }
        public virtual DbSet<News_Functions> News_Functions { get; set; }
        public virtual DbSet<News_Menu> News_Menu { get; set; }
        public virtual DbSet<News_Order> News_Order { get; set; }
        public virtual DbSet<News_Post> News_Post { get; set; }
        public virtual DbSet<News_Title> News_Title { get; set; }
        public virtual DbSet<NganhNgheKinhDoanh> NganhNgheKinhDoanhs { get; set; }
        public virtual DbSet<NhomHangHoa_NganhNgheKinhDoanh> NhomHangHoa_NganhNgheKinhDoanh { get; set; }
        public virtual DbSet<News_Categories> News_Categories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<News_User> News_User { get; set; }
        public virtual DbSet<News_UserGroup> News_UserGroup { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserGroupRole> UserGroupRoles { get; set; }
        public virtual DbSet<TinhThanh_QuanHuyen> TinhThanh_QuanHuyen { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<NumberUserAccess> NumberUserAccesses { get; set; }
        public virtual DbSet<PageView> PageViews { get; set; }
        public virtual DbSet<UserVisit> UserVisits { get; set; }
        public virtual DbSet<ArticleTag> ArticleTags { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<MenuTag> MenuTags { get; set; }
        public virtual DbSet<News_Articles> News_Articles { get; set; }
        public virtual DbSet<AnhTinhNangNghanhNghe> AnhTinhNangNghanhNghes { get; set; }
        public virtual DbSet<TinhNangNghanhNghe> TinhNangNghanhNghes { get; set; }
        public virtual DbSet<SalesDevice> SalesDevices { get; set; }
        public virtual DbSet<SalesGroupDevice> SalesGroupDevices { get; set; }
        public virtual DbSet<SalesImgDevice> SalesImgDevices { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<NotificationSoftware> NotificationSoftwares { get; set; }
        public virtual DbSet<DM_XaPhuong> DM_XaPhuong { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<DM_GoiDichVu> DM_GoiDichVu { get; set; }
        public virtual DbSet<LichSuGiaHanCuaHang> LichSuGiaHanCuaHangs { get; set; }
        public virtual DbSet<RegisterServiceSm> RegisterServiceSms { get; set; }
        public virtual DbSet<SupplierSm> SupplierSms { get; set; }
        public virtual DbSet<CuaHangNapTienDichVu> CuaHangNapTienDichVus { get; set; }
        public virtual DbSet<LH_HoiDap> LH_HoiDap { get; set; }
        public virtual DbSet<LH_NhomNganh> LH_NhomNganh { get; set; }
        public virtual DbSet<LH_NhomNganh_TinhNang> LH_NhomNganh_TinhNang { get; set; }
        public virtual DbSet<LH_TinhNang> LH_TinhNang { get; set; }
        public virtual DbSet<SeoRedirectUrl> SeoRedirectUrls { get; set; }
        public virtual DbSet<DanhMucThuocQuocGia> DanhMucThuocQuocGias { get; set; }
        public virtual DbSet<QueueJob> QueueJobs { get; set; }
        public virtual DbSet<QueueJobDone> QueueJobDones { get; set; }
    }
}
