//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHangDangKy
    {
        public string SoDienThoai { get; set; }
        public string SubDomain { get; set; }
        public string TenCuaHang { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> ID_NganhKinhDoanh { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string UserKT { get; set; }
        public string MatKhauKT { get; set; }
        public string MaKichHoat { get; set; }
        public Nullable<System.DateTime> HanSuDung { get; set; }
        public Nullable<int> SoLanKichHoat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.Guid> ID_TinhThanh_QuanHuyen { get; set; }
        public string ThietBi_DK { get; set; }
        public string HeDieuHanh_DK { get; set; }
        public string KhuVuc_DK { get; set; }
        public string DiaChiIP_DK { get; set; }
        public string TrinhDuyet_DK { get; set; }
        public string ID_GoiDichVu { get; set; }
        public Nullable<int> version { get; set; }
        public string SubDomainWeb { get; set; }
        public string Domain { get; set; }
        public Nullable<bool> IsCreateDatabase { get; set; }
    
        public virtual NganhNgheKinhDoanh NganhNgheKinhDoanh { get; set; }
        public virtual CuaHangDangKy CuaHangDangKy1 { get; set; }
        public virtual CuaHangDangKy CuaHangDangKy2 { get; set; }
        public virtual TinhThanh_QuanHuyen TinhThanh_QuanHuyen { get; set; }
        public virtual DM_GoiDichVu DM_GoiDichVu { get; set; }
    }
}
