//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHangNapTienDichVu
    {
        public System.Guid ID { get; set; }
        public string TenKhachHang { get; set; }
        public string SoDienThoaiCuaHang { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayXacNhan { get; set; }
        public Nullable<System.Guid> ID_PhieuNhan { get; set; }
    }
}
