//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public Nullable<System.Guid> DistrictCity { get; set; }
        public Nullable<System.Guid> TypeBusiness { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string Images { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Url { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> prioritize { get; set; }
    }
}
