//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucThuocQuocGia
    {
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
        public string SoDangKy { get; set; }
        public string HoatChatChinh { get; set; }
        public string HamLuong { get; set; }
        public string QuyCachDongGoi { get; set; }
        public string HangSanXuat { get; set; }
        public string NuocSanXuat { get; set; }
        public string DonViTinh { get; set; }
    }
}
