//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GoiDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_GoiDichVu()
        {
            this.CuaHangDangKies = new HashSet<CuaHangDangKy>();
            this.LichSuGiaHanCuaHangs = new HashSet<LichSuGiaHanCuaHang>();
        }
    
        public string ID { get; set; }
        public string TenGoi { get; set; }
        public int SLMatHang { get; set; }
        public int SLChiNhanh { get; set; }
        public int SLNguoiDung { get; set; }
        public decimal Gia { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuaHangDangKy> CuaHangDangKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGiaHanCuaHang> LichSuGiaHanCuaHangs { get; set; }
    }
}
