//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_HangHoa()
        {
            this.DonViQuiDois = new HashSet<DonViQuiDoi>();
        }
    
        public System.Guid ID { get; set; }
        public string TenHangHoa { get; set; }
        public bool LaHangHoa { get; set; }
        public Nullable<System.Guid> ID_NhomHang { get; set; }
        public Nullable<System.Guid> ID_PhanLoai { get; set; }
        public Nullable<System.Guid> ID_QuocGia { get; set; }
        public Nullable<System.Guid> ID_DoiTuong { get; set; }
        public Nullable<double> QuyCach { get; set; }
        public Nullable<System.Guid> ID_DVTQuyCach { get; set; }
        public Nullable<int> LoaiBaoHanh { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
        public string TenTGBaoHanh { get; set; }
        public double ChiPhiThucHien { get; set; }
        public bool ChiPhiTinhTheoPT { get; set; }
        public Nullable<bool> TinhCPSauChietKhau { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoPhutThucHien { get; set; }
        public Nullable<double> ChietKhauMD_NV { get; set; }
        public Nullable<bool> ChietKhauMD_NVTheoPT { get; set; }
        public Nullable<int> TinhGiaVon { get; set; }
        public bool TheoDoi { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string TenKhac { get; set; }
        public string ChatLieu { get; set; }
        public string KichCo { get; set; }
        public string MauSac { get; set; }
    
        public virtual DM_NhomHangHoa DM_NhomHangHoa { get; set; }
        public virtual DM_PhanLoaiHangHoaDichVu DM_PhanLoaiHangHoaDichVu { get; set; }
        public virtual DM_QuocGia DM_QuocGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonViQuiDoi> DonViQuiDois { get; set; }
    }
}
