//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NhomHangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_NhomHangHoa()
        {
            this.DM_HangHoa = new HashSet<DM_HangHoa>();
            this.DM_NhomHangHoa1 = new HashSet<DM_NhomHangHoa>();
            this.NhomHangHoa_NganhNgheKinhDoanh = new HashSet<NhomHangHoa_NganhNgheKinhDoanh>();
        }
    
        public System.Guid ID { get; set; }
        public string MaNhomHangHoa { get; set; }
        public string TenNhomHangHoa { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.Guid> ID_Parent { get; set; }
        public bool LaNhomHangHoa { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<bool> HienThi_Chinh { get; set; }
        public Nullable<bool> HienThi_Phu { get; set; }
        public string MayIn { get; set; }
        public Nullable<System.Guid> ID_Kho { get; set; }
        public Nullable<bool> HienThi_BanThe { get; set; }
        public Nullable<int> MauHienThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_HangHoa> DM_HangHoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_NhomHangHoa> DM_NhomHangHoa1 { get; set; }
        public virtual DM_NhomHangHoa DM_NhomHangHoa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomHangHoa_NganhNgheKinhDoanh> NhomHangHoa_NganhNgheKinhDoanh { get; set; }
    }
}
