//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_QuanHuyen
    {
        public System.Guid ID { get; set; }
        public string MaQuanHuyen { get; set; }
        public string TenQuanHuyen { get; set; }
        public System.Guid ID_TinhThanh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DM_TinhThanh DM_TinhThanh { get; set; }
    }
}
