//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TinhThanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_TinhThanh()
        {
            this.DM_QuanHuyen = new HashSet<DM_QuanHuyen>();
        }
    
        public System.Guid ID { get; set; }
        public string MaTinhThanh { get; set; }
        public string TenTinhThanh { get; set; }
        public Nullable<System.Guid> ID_QuocGia { get; set; }
        public Nullable<System.Guid> ID_VungMien { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_QuanHuyen> DM_QuanHuyen { get; set; }
        public virtual DM_QuocGia DM_QuocGia { get; set; }
        public virtual DM_VungMien DM_VungMien { get; set; }
    }
}
