//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViQuiDoi
    {
        public string MaHangHoa { get; set; }
        public System.Guid ID_HangHoa { get; set; }
        public string TenDonViTinh { get; set; }
        public double TyLeChuyenDoi { get; set; }
        public bool LaDonViChuan { get; set; }
        public double GiaNhap { get; set; }
        public double GiaBan { get; set; }
        public string GhiChu { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    
        public virtual DM_HangHoa DM_HangHoa { get; set; }
    }
}
