//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LH_NhomNganh_TinhNang
    {
        public long ID { get; set; }
        public long ID_TinhNang { get; set; }
        public long ID_NhomNganh { get; set; }
    
        public virtual LH_NhomNganh LH_NhomNganh { get; set; }
        public virtual LH_TinhNang LH_TinhNang { get; set; }
    }
}
