//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LH_TinhNang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LH_TinhNang()
        {
            this.LH_NhomNganh_TinhNang = new HashSet<LH_NhomNganh_TinhNang>();
        }
    
        public long ID { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<long> ID_Cha { get; set; }
        public string NoiDung { get; set; }
        public string Video { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> ViTri { get; set; }
        public string TenTiengViet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LH_NhomNganh_TinhNang> LH_NhomNganh_TinhNang { get; set; }
    }
}
