//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaHanCuaHang
    {
        public long ID { get; set; }
        public string SubDomain { get; set; }
        public string ID_GoiDichVu { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> LoaiGiaHan { get; set; }
        public Nullable<decimal> GiaGoiHienTai { get; set; }
        public string ThoiGianGiaHan { get; set; }
    
        public virtual DM_GoiDichVu DM_GoiDichVu { get; set; }
    }
}
