//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_FunctionList
    {
        public int ID { get; set; }
        public string FunctionName { get; set; }
        public string Url { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
