//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Articles
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string UrlImage { get; set; }
        public string Content { get; set; }
        public string Tag { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Salary { get; set; }
        public string Address { get; set; }
        public string Experience { get; set; }
        public string Position { get; set; }
        public string Degree { get; set; }
        public string WorkingForm { get; set; }
        public string NumberOfRecruits { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Trades { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Url { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
    }
}
