//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Title
    {
        public System.Guid ID { get; set; }
        public Nullable<int> PostGroupID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfPosts { get; set; }
        public string Avatar { get; set; }
        public string UrlTitle { get; set; }
        public string KeywordTitle { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CrreateBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
