//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Post
    {
        public int ID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public string Content { get; set; }
        public string Avatar { get; set; }
        public string Video { get; set; }
        public string KeywordPost { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Salary { get; set; }
        public string Address { get; set; }
        public string Experience { get; set; }
        public string Position { get; set; }
        public string Degree { get; set; }
        public string WorkingForm { get; set; }
        public string NumberOfRecruits { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Trades { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
