//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NganhNgheKinhDoanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NganhNgheKinhDoanh()
        {
            this.CuaHangDangKies = new HashSet<CuaHangDangKy>();
            this.HT_Quyen_NganhNgheKinhDoanh = new HashSet<HT_Quyen_NganhNgheKinhDoanh>();
            this.NhomHangHoa_NganhNgheKinhDoanh = new HashSet<NhomHangHoa_NganhNgheKinhDoanh>();
        }
    
        public System.Guid ID { get; set; }
        public string MaNganhNghe { get; set; }
        public string TenNganhNghe { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Image { get; set; }
        public string ImageMobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuaHangDangKy> CuaHangDangKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_Quyen_NganhNgheKinhDoanh> HT_Quyen_NganhNgheKinhDoanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhomHangHoa_NganhNgheKinhDoanh> NhomHangHoa_NganhNgheKinhDoanh { get; set; }
    }
}
