//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomHangHoa_NganhNgheKinhDoanh
    {
        public System.Guid ID { get; set; }
        public System.Guid ID_NhomHangHoa { get; set; }
        public System.Guid ID_NganhNgheKinhDoanh { get; set; }
    
        public virtual DM_NhomHangHoa DM_NhomHangHoa { get; set; }
        public virtual NganhNgheKinhDoanh NganhNgheKinhDoanh { get; set; }
    }
}
