//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberUserAccess
    {
        public int ID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Sys_Android { get; set; }
        public Nullable<int> Sys_MAC_OS { get; set; }
        public Nullable<int> Sys_Linux { get; set; }
        public Nullable<int> Sys_Windows { get; set; }
        public Nullable<int> Sys_Other { get; set; }
        public Nullable<int> Device_TV { get; set; }
        public Nullable<int> Device_Tablet { get; set; }
        public Nullable<int> Device_Mobile { get; set; }
        public Nullable<int> Device_Desktop { get; set; }
    }
}
