//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueJob
    {
        public System.Guid ID { get; set; }
        public System.Guid IDNhatKySuDung { get; set; }
        public string Subdomain { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
        public int TrangThai { get; set; }
        public int SoLanDaChay { get; set; }
    }
}
