//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterServiceSm
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ID_SupplierSms { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string SoDienThoaiCuaHang { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Note { get; set; }
        public string UserActivated { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual SupplierSm SupplierSm { get; set; }
    }
}
