//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesImgDevice
    {
        public long ID { get; set; }
        public Nullable<long> SalesDeviceID { get; set; }
        public string SrcImage { get; set; }
    
        public virtual SalesDevice SalesDevice { get; set; }
    }
}
