//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesDevice()
        {
            this.SalesImgDevices = new HashSet<SalesImgDevice>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Trademark { get; set; }
        public Nullable<int> ViewBuy { get; set; }
        public Nullable<int> TimeGuarantee { get; set; }
        public Nullable<long> GroupDeviceId { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<System.Guid> EditUser { get; set; }
        public string SpecialPoint { get; set; }
        public string ApplicationReal { get; set; }
        public string DigitalInformation { get; set; }
        public Nullable<bool> Status { get; set; }
        public int Price { get; set; }
        public Nullable<int> PriceSale { get; set; }
        public Nullable<bool> IsSalePrice { get; set; }
        public string Url { get; set; }
        public string Encoder { get; set; }
    
        public virtual SalesGroupDevice SalesGroupDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesImgDevice> SalesImgDevices { get; set; }
    }
}
