//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhNangNghanhNghe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinhNangNghanhNghe()
        {
            this.AnhTinhNangNghanhNghes = new HashSet<AnhTinhNangNghanhNghe>();
        }
    
        public long Id { get; set; }
        public System.Guid Id_NganhNghe { get; set; }
        public string TenTinhNang { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
        public System.Guid UserEdit { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> STT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhTinhNangNghanhNghe> AnhTinhNangNghanhNghes { get; set; }
    }
}
