//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_banhang24vn
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVisit
    {
        public System.Guid ID { get; set; }
        public string Ip { get; set; }
        public string Browser { get; set; }
        public string City { get; set; }
        public string Device { get; set; }
        public string Country { get; set; }
        public string System { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
