//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banhang24.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("banhang24.Resources.NotificationResource", typeof(NotificationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        public static string Header_DoiTac {
            get {
                return ResourceManager.GetString("Header_DoiTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch.
        /// </summary>
        public static string Header_GiaoDich {
            get {
                return ResourceManager.GetString("Header_GiaoDich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa mẫu in thất bại.
        /// </summary>
        public static string MauInDeleteError {
            get {
                return ResourceManager.GetString("MauInDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa mẫu in thành công.
        /// </summary>
        public static string MauInDeleteSuccess {
            get {
                return ResourceManager.GetString("MauInDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên mẫu in.
        /// </summary>
        public static string MauInErrorName {
            get {
                return ResourceManager.GetString("MauInErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới mẫu in thất bại.
        /// </summary>
        public static string MauInInsertError {
            get {
                return ResourceManager.GetString("MauInInsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới mẫu in thành công.
        /// </summary>
        public static string MauInInsertSuccess {
            get {
                return ResourceManager.GetString("MauInInsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép mẫu in thất bại.
        /// </summary>
        public static string MauInSaveError {
            get {
                return ResourceManager.GetString("MauInSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép mẫu in thành công.
        /// </summary>
        public static string MauInSaveSuccess {
            get {
                return ResourceManager.GetString("MauInSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập mẫu in thất bại.
        /// </summary>
        public static string MauInSetupError {
            get {
                return ResourceManager.GetString("MauInSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết lập mẫu in thành công.
        /// </summary>
        public static string MauInSetupSuccess {
            get {
                return ResourceManager.GetString("MauInSetupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật mẫu in thất bại.
        /// </summary>
        public static string MauInUpdateError {
            get {
                return ResourceManager.GetString("MauInUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật mẫu in thành công.
        /// </summary>
        public static string MauInUpdateSuccess {
            get {
                return ResourceManager.GetString("MauInUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string SoQuy_KhacHang {
            get {
                return ResourceManager.GetString("SoQuy_KhacHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        public static string SoQuy_NhaCungCap {
            get {
                return ResourceManager.GetString("SoQuy_NhaCungCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string SoQuy_NhanVien {
            get {
                return ResourceManager.GetString("SoQuy_NhanVien", resourceCulture);
            }
        }
    }
}
