// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateSP_getlistHangHoa_XNT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateSP_getlistHangHoa_XNT));
        
        string IMigrationMetadata.Id
        {
            get { return "201801220450047_CreateSP_getlistHangHoa_XNT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
