// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sp_chotso_20180123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sp_chotso_20180123));
        
        string IMigrationMetadata.Id
        {
            get { return "201801230709114_sp_chotso_20180123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
