// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addUpdateSP_20180514 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUpdateSP_20180514));
        
        string IMigrationMetadata.Id
        {
            get { return "201805150856149_addUpdateSP_20180514"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
