// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addUpdateSP_20181113 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUpdateSP_20181113));
        
        string IMigrationMetadata.Id
        {
            get { return "201811131027339_addUpdateSP_20181113"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
