// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddUpdateSP_20191230 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUpdateSP_20191230));
        
        string IMigrationMetadata.Id
        {
            get { return "201912300845490_AddUpdateSP_20191230"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
