// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExecTonLuyKe_20190629 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExecTonLuyKe_20190629));
        
        string IMigrationMetadata.Id
        {
            get { return "201906291055574_ExecTonLuyKe_20190629"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
