// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSP_BaoCaoKho_XuatDichVuDinhLuong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSP_BaoCaoKho_XuatDichVuDinhLuong));
        
        string IMigrationMetadata.Id
        {
            get { return "201901190203308_AddSP_BaoCaoKho_XuatDichVuDinhLuong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
