// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SpUpdate_20210414 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpUpdate_20210414));
        
        string IMigrationMetadata.Id
        {
            get { return "202104141550414_SpUpdate_20210414"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
