// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTableBH_ChiTiet_DinhDanh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableBH_ChiTiet_DinhDanh));
        
        string IMigrationMetadata.Id
        {
            get { return "202306270755243_addTableBH_ChiTiet_DinhDanh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
