// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Kangjin_AddUpdateSP_20230209 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kangjin_AddUpdateSP_20230209));
        
        string IMigrationMetadata.Id
        {
            get { return "202302090143320_Kangjin_AddUpdateSP_20230209"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
