// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class kangJin_UpdateSP_20240204 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kangJin_UpdateSP_20240204));
        
        string IMigrationMetadata.Id
        {
            get { return "202402041358418_kangJin_UpdateSP_20240204"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
