// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KangJin_AddUpdateSP_20240108 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KangJin_AddUpdateSP_20240108));
        
        string IMigrationMetadata.Id
        {
            get { return "202401081018071_KangJin_AddUpdateSP_20240108"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
